rootcolor=0x{color1.strip}ff
bordercolor=0x{color1.strip}ff
focuscolor=0x{color5.strip}ff
maximizescreencolor=0x{color5.strip}ff
urgentcolor=0xad401fff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff
