exec-once=waybar -c ~/.config/waybar/config-mango -s ~/.config/waybar/style-mango.css 
exec-once=brightnessctl -s set 65000
exec-once=awww-daemon 
exec-once=omvoid-cmd-first-run
exec-once=~/.config/swayosd/launch.sh 
exec-once=omvoid-powerevent-monitor
exec-once=omvoid-battery-monitor-launcher 
exec-once=caffeine 
exec-once=wl-clip-persist --clipboard regular 
exec-once=wl-paste --type text --watch cliphist store  # Stores only text data
exec-once=wl-paste --type image --watch cliphist store  # Stores only image data
exec-once=runsvdir -P ~/.config/service 
exec-once=omvoid-bar-playerctl-loop
exec-once=crystal-dock
