windowrule=isfloating:1,isnoshadow:1,ignore_maximize:1,ignore_minimize:1,width:480,height:270,appid:brave-browser,title:Picture-in-Picture
windowrule=isfloating:1,noopenmaximized:1,appid:brave-browser,title:^(Save|Open|Export)
windowrule=isfloating:1,noopenmaximized:1,appid:zen,title:^(Save|Open|Export)
windowrule=isfloating:1,noopenmaximized:1,title:^(Open File|Save File|Preferences|Properties|About)
windowrule=isfloating:1,center:1,width:900,height:700,appid:pavucontrol
windowrule=isfloating:1,center:1,width:700,height:500,appid:blueman-manager
windowrule=isfloating:1,center:1,width:900,height:600,title:^(nmtui)
windowrule=isfloating:1,center:1,width:800,height:600,appid:qt5ct
windowrule=isfloating:1,center:1,width:800,height:600,appid:nwg-look
windowrule=isfloating:1,center:1,width:1300,height:800,appid:imv
windowrule=isfloating:1,center:1,width:400,height:400,appid:(org.gnome.Calculator)
windowrule=isfloating:1,center:1,width:1300,height:750,appid:rmpc
windowrule=focused_opacity:0.9,appid:org.gnome.Nautilus
windowrule=focused_opacity:0.9,appid:org.telegram.deskto
windowrule=isfloating:1,center:1,width:800,height:600,appid:TUI.float
