#!/usr/bin/env bash
source ~/.cache/wal/dwmblocks

function powermenu {
	options="Cancel\nShutdown\nReboot\nSleep\nLock"
	selected=$(echo -e $options | rofi -dmenu -theme ~/.config/rofi/menu-style-minimal.rasi)
	if [[ $selected = "Shutdown" ]]; then
		systemctl poweroff
	elif [[ $selected = "Reboot" ]]; then
		systemctl reboot
	elif [[ $selected = "Sleep" ]]; then
		systemctl suspend
	elif [[ $selected = "Lock" ]]; then
		slock
	elif [[ $selected = "Cancel": ]]; then
		return
	fi
}

case $BLOCK_BUTTON in
	1) powermenu ;;
	3) notify-send "Powermenu" ;;
esac

echo " ^c$color0^^b$color3^         ^d^"

