[General]
activeIndicatorColor=#ff8c00
activeIndicatorColor2D=#ffbf00
backgroundColor=#6b638abd
backgroundColor2D=#38bbbbbb
borderColor=#99addd
bouncingLauncherIcon=false
firstRunWindowCountIndicator=false
floatingMargin=4
inactiveIndicatorColor=#008b8b
inactiveIndicatorColor2D=#00ffff
maximumIconSize=60
minimumIconSize=40
panelStyle=2
showTooltip=true
spacingFactor=0.5
tooltipFontSize=9
zoomingAnimationSpeed=11

[Application%20Menu]
backgroundAlpha=0.8
fontSize=14
label=Applications

[Clock]
clockFontFamily=CaskaydiaMono Nerd Font
fontScaleFactor=1
use24HourClock=true
