[[mgr.prepend_keymap]]
on   = [ "D" ]
run  = 'shell -- ripdrag "$@"'
desc = "Drag out selected files"
[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]
[[mgr.prepend_keymap]]
on   = ["p"]
run  = "shell \"wl-paste | sed 's|^file://||' | xargs -d '\\n' cp -t ./\" --confirm"
desc = "Paste from Nautilus"
