# More option see https://github.com/DreamMaoMao/mango/wiki/
source=~/.cache/wal/colors-mango.conf
source=~/.config/mango/conf/autostart.conf
source=~/.config/mango/conf/monitors.conf
source=~/.config/mango/conf/env.conf
source=~/.config/mango/conf/windowrules.conf
source=~/.config/mango/conf/keybindings.conf
source=~/.config/mango/conf/effects.conf
source=~/.config/mango/conf/layout.conf
source=~/.config/mango/conf/misc.conf
